call uic.bat aboutSSVG
call uic.bat editmandialog
call uic.bat edittimedialog
call uic.bat flightreviewcontrol
call uic.bat ftasettingdialog
call uic.bat mainwindow
call uic.bat newflightplandialog
call uic.bat orbitoptimizedialog
call uic.bat reviewthroughoutcontrol
call uic.bat showorbitcontrol
call uic.bat descriptioneditor
call uic.bat maneuverdescription
