# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editmandialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editmandialog(object):
    def setupUi(self, editmandialog):
        editmandialog.setObjectName("editmandialog")
        editmandialog.setWindowModality(QtCore.Qt.WindowModal)
        editmandialog.resize(640, 320)
        editmandialog.setModal(True)
        self.label = QtWidgets.QLabel(editmandialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.mantype = QtWidgets.QComboBox(editmandialog)
        self.mantype.setGeometry(QtCore.QRect(190, 10, 81, 22))
        self.mantype.setMaxVisibleItems(7)
        self.mantype.setObjectName("mantype")
        self.label_time = QtWidgets.QLabel(editmandialog)
        self.label_time.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_time.setObjectName("label_time")
        self.isotedit = QtWidgets.QLineEdit(editmandialog)
        self.isotedit.setGeometry(QtCore.QRect(80, 60, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.isotedit.setFont(font)
        self.isotedit.setObjectName("isotedit")
        self.label_3 = QtWidgets.QLabel(editmandialog)
        self.label_3.setGeometry(QtCore.QRect(80, 43, 201, 16))
        self.label_3.setObjectName("label_3")
        self.jdedit = QtWidgets.QLineEdit(editmandialog)
        self.jdedit.setGeometry(QtCore.QRect(280, 60, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.jdedit.setFont(font)
        self.jdedit.setObjectName("jdedit")
        self.label_4 = QtWidgets.QLabel(editmandialog)
        self.label_4.setGeometry(QtCore.QRect(330, 44, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(editmandialog)
        self.label_5.setGeometry(QtCore.QRect(100, 90, 61, 16))
        self.label_5.setObjectName("label_5")
        self.parameters = QtWidgets.QTableWidget(editmandialog)
        self.parameters.setGeometry(QtCore.QRect(100, 110, 521, 164))
        self.parameters.setCornerButtonEnabled(False)
        self.parameters.setRowCount(8)
        self.parameters.setColumnCount(2)
        self.parameters.setObjectName("parameters")
        self.parameters.horizontalHeader().setVisible(False)
        self.parameters.verticalHeader().setVisible(False)
        self.parameters.verticalHeader().setDefaultSectionSize(20)
        self.parameters.verticalHeader().setMinimumSectionSize(20)
        self.finishbutton = QtWidgets.QPushButton(editmandialog)
        self.finishbutton.setGeometry(QtCore.QRect(330, 290, 101, 23))
        self.finishbutton.setAutoDefault(False)
        self.finishbutton.setObjectName("finishbutton")
        self.cancelbutton = QtWidgets.QPushButton(editmandialog)
        self.cancelbutton.setGeometry(QtCore.QRect(540, 290, 75, 23))
        self.cancelbutton.setAutoDefault(False)
        self.cancelbutton.setObjectName("cancelbutton")
        self.showorbit = QtWidgets.QPushButton(editmandialog)
        self.showorbit.setEnabled(False)
        self.showorbit.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.showorbit.setAutoDefault(False)
        self.showorbit.setObjectName("showorbit")
        self.applymantype = QtWidgets.QPushButton(editmandialog)
        self.applymantype.setGeometry(QtCore.QRect(274, 9, 41, 23))
        self.applymantype.setAutoDefault(False)
        self.applymantype.setObjectName("applymantype")
        self.mantypedisp = QtWidgets.QLabel(editmandialog)
        self.mantypedisp.setGeometry(QtCore.QRect(100, 10, 71, 16))
        self.mantypedisp.setText("")
        self.mantypedisp.setObjectName("mantypedisp")
        self.computeFTA = QtWidgets.QPushButton(editmandialog)
        self.computeFTA.setEnabled(False)
        self.computeFTA.setGeometry(QtCore.QRect(10, 140, 75, 23))
        self.computeFTA.setAutoDefault(False)
        self.computeFTA.setObjectName("computeFTA")
        self.finish_exec = QtWidgets.QPushButton(editmandialog)
        self.finish_exec.setEnabled(False)
        self.finish_exec.setGeometry(QtCore.QRect(210, 290, 101, 23))
        self.finish_exec.setAutoDefault(False)
        self.finish_exec.setObjectName("finish_exec")
        self.duration = QtWidgets.QLineEdit(editmandialog)
        self.duration.setEnabled(False)
        self.duration.setGeometry(QtCore.QRect(460, 60, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.duration.setFont(font)
        self.duration.setObjectName("duration")
        self.applyduration = QtWidgets.QPushButton(editmandialog)
        self.applyduration.setEnabled(False)
        self.applyduration.setGeometry(QtCore.QRect(584, 59, 41, 23))
        self.applyduration.setAutoDefault(False)
        self.applyduration.setObjectName("applyduration")
        self.label_duration = QtWidgets.QLabel(editmandialog)
        self.label_duration.setEnabled(False)
        self.label_duration.setGeometry(QtCore.QRect(461, 43, 111, 16))
        self.label_duration.setTextFormat(QtCore.Qt.PlainText)
        self.label_duration.setObjectName("label_duration")
        self.optimize = QtWidgets.QPushButton(editmandialog)
        self.optimize.setEnabled(False)
        self.optimize.setGeometry(QtCore.QRect(10, 170, 75, 23))
        self.optimize.setAutoDefault(False)
        self.optimize.setObjectName("optimize")

        self.retranslateUi(editmandialog)
        QtCore.QMetaObject.connectSlotsByName(editmandialog)
        editmandialog.setTabOrder(self.mantype, self.applymantype)
        editmandialog.setTabOrder(self.applymantype, self.isotedit)
        editmandialog.setTabOrder(self.isotedit, self.jdedit)
        editmandialog.setTabOrder(self.jdedit, self.parameters)
        editmandialog.setTabOrder(self.parameters, self.showorbit)
        editmandialog.setTabOrder(self.showorbit, self.computeFTA)
        editmandialog.setTabOrder(self.computeFTA, self.finish_exec)
        editmandialog.setTabOrder(self.finish_exec, self.finishbutton)
        editmandialog.setTabOrder(self.finishbutton, self.cancelbutton)

    def retranslateUi(self, editmandialog):
        _translate = QtCore.QCoreApplication.translate
        editmandialog.setWindowTitle(_translate("editmandialog", "Maneuver Editor"))
        self.label.setText(_translate("editmandialog", "Maneuver Type"))
        self.mantype.setToolTip(_translate("editmandialog", "Select maneuver type and click Apply button"))
        self.label_time.setText(_translate("editmandialog", "Date&Time"))
        self.isotedit.setToolTip(_translate("editmandialog", "Date and Time (ISOT format)"))
        self.label_3.setText(_translate("editmandialog", "ISOT : yyyy-mm-ddThh:mm:ss.ssssss"))
        self.jdedit.setToolTip(_translate("editmandialog", "Date and Time (Julian day)"))
        self.label_4.setText(_translate("editmandialog", "JD"))
        self.label_5.setText(_translate("editmandialog", "Parameters"))
        self.finishbutton.setToolTip(_translate("editmandialog", "Finish editing"))
        self.finishbutton.setText(_translate("editmandialog", "Finish"))
        self.cancelbutton.setToolTip(_translate("editmandialog", "Discard changes and quit editing"))
        self.cancelbutton.setText(_translate("editmandialog", "Cancel"))
        self.showorbit.setToolTip(_translate("editmandialog", "Show orbit"))
        self.showorbit.setText(_translate("editmandialog", "SHOW Orbit"))
        self.applymantype.setToolTip(_translate("editmandialog", "Select maneuver type and click Apply button"))
        self.applymantype.setText(_translate("editmandialog", "Apply"))
        self.computeFTA.setToolTip(_translate("editmandialog", "Comute fixed time arrival guidance"))
        self.computeFTA.setText(_translate("editmandialog", "FTA"))
        self.finish_exec.setToolTip(_translate("editmandialog", "Finish editing and execute this maneuver"))
        self.finish_exec.setText(_translate("editmandialog", "Finish and Exec"))
        self.duration.setToolTip(_translate("editmandialog", "Flight Duration for FLYTO"))
        self.applyduration.setToolTip(_translate("editmandialog", "Apply the flight duration to Date&Time"))
        self.applyduration.setText(_translate("editmandialog", "Apply"))
        self.label_duration.setText(_translate("editmandialog", "Duration (days)"))
        self.optimize.setToolTip(_translate("editmandialog", "Optimize Assistant"))
        self.optimize.setText(_translate("editmandialog", "OPTIMIZE"))

