# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editmandialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editmandialog(object):
    def setupUi(self, editmandialog):
        editmandialog.setObjectName("editmandialog")
        editmandialog.setWindowModality(QtCore.Qt.WindowModal)
        editmandialog.resize(640, 320)
        editmandialog.setMinimumSize(QtCore.QSize(640, 320))
        editmandialog.setMaximumSize(QtCore.QSize(640, 320))
        editmandialog.setModal(True)
        self.label = QtWidgets.QLabel(editmandialog)
        self.label.setGeometry(QtCore.QRect(0, 10, 51, 21))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.mantype = QtWidgets.QComboBox(editmandialog)
        self.mantype.setGeometry(QtCore.QRect(60, 10, 91, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mantype.setFont(font)
        self.mantype.setMaxVisibleItems(7)
        self.mantype.setFrame(True)
        self.mantype.setObjectName("mantype")
        self.label_time = QtWidgets.QLabel(editmandialog)
        self.label_time.setGeometry(QtCore.QRect(0, 60, 71, 16))
        self.label_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time.setObjectName("label_time")
        self.isotedit = QtWidgets.QLineEdit(editmandialog)
        self.isotedit.setGeometry(QtCore.QRect(180, 40, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.isotedit.setFont(font)
        self.isotedit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.isotedit.setToolTip("")
        self.isotedit.setFrame(False)
        self.isotedit.setReadOnly(True)
        self.isotedit.setObjectName("isotedit")
        self.label_3 = QtWidgets.QLabel(editmandialog)
        self.label_3.setGeometry(QtCore.QRect(90, 40, 81, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.jdedit = QtWidgets.QLineEdit(editmandialog)
        self.jdedit.setGeometry(QtCore.QRect(180, 60, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.jdedit.setFont(font)
        self.jdedit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.jdedit.setToolTip("")
        self.jdedit.setFrame(False)
        self.jdedit.setReadOnly(True)
        self.jdedit.setObjectName("jdedit")
        self.label_4 = QtWidgets.QLabel(editmandialog)
        self.label_4.setGeometry(QtCore.QRect(90, 60, 81, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(editmandialog)
        self.label_5.setGeometry(QtCore.QRect(0, 170, 71, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.parameters = QtWidgets.QTableWidget(editmandialog)
        self.parameters.setGeometry(QtCore.QRect(80, 110, 352, 162))
        self.parameters.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.parameters.setCornerButtonEnabled(False)
        self.parameters.setRowCount(8)
        self.parameters.setColumnCount(2)
        self.parameters.setObjectName("parameters")
        self.parameters.horizontalHeader().setVisible(False)
        self.parameters.verticalHeader().setVisible(False)
        self.parameters.verticalHeader().setDefaultSectionSize(20)
        self.parameters.verticalHeader().setMinimumSectionSize(20)
        self.finishbutton = QtWidgets.QPushButton(editmandialog)
        self.finishbutton.setGeometry(QtCore.QRect(350, 290, 101, 23))
        self.finishbutton.setAutoDefault(False)
        self.finishbutton.setObjectName("finishbutton")
        self.cancelbutton = QtWidgets.QPushButton(editmandialog)
        self.cancelbutton.setGeometry(QtCore.QRect(520, 290, 91, 23))
        self.cancelbutton.setAutoDefault(False)
        self.cancelbutton.setObjectName("cancelbutton")
        self.showorbit = QtWidgets.QPushButton(editmandialog)
        self.showorbit.setEnabled(False)
        self.showorbit.setGeometry(QtCore.QRect(520, 70, 91, 23))
        self.showorbit.setAutoDefault(False)
        self.showorbit.setObjectName("showorbit")
        self.computeFTA = QtWidgets.QPushButton(editmandialog)
        self.computeFTA.setEnabled(False)
        self.computeFTA.setGeometry(QtCore.QRect(520, 110, 91, 23))
        self.computeFTA.setAutoDefault(False)
        self.computeFTA.setObjectName("computeFTA")
        self.finish_exec = QtWidgets.QPushButton(editmandialog)
        self.finish_exec.setEnabled(False)
        self.finish_exec.setGeometry(QtCore.QRect(210, 290, 101, 23))
        self.finish_exec.setAutoDefault(False)
        self.finish_exec.setObjectName("finish_exec")
        self.duration = QtWidgets.QLineEdit(editmandialog)
        self.duration.setEnabled(True)
        self.duration.setGeometry(QtCore.QRect(180, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.duration.setFont(font)
        self.duration.setFocusPolicy(QtCore.Qt.NoFocus)
        self.duration.setToolTip("")
        self.duration.setFrame(False)
        self.duration.setReadOnly(True)
        self.duration.setObjectName("duration")
        self.EditDateTime = QtWidgets.QPushButton(editmandialog)
        self.EditDateTime.setEnabled(True)
        self.EditDateTime.setGeometry(QtCore.QRect(340, 70, 91, 23))
        self.EditDateTime.setAutoDefault(False)
        self.EditDateTime.setObjectName("EditDateTime")
        self.label_duration = QtWidgets.QLabel(editmandialog)
        self.label_duration.setEnabled(True)
        self.label_duration.setGeometry(QtCore.QRect(90, 80, 81, 16))
        self.label_duration.setTextFormat(QtCore.Qt.PlainText)
        self.label_duration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_duration.setObjectName("label_duration")
        self.optimize = QtWidgets.QPushButton(editmandialog)
        self.optimize.setEnabled(False)
        self.optimize.setGeometry(QtCore.QRect(520, 150, 91, 23))
        self.optimize.setAutoDefault(False)
        self.optimize.setObjectName("optimize")
        self.label_Click = QtWidgets.QLabel(editmandialog)
        self.label_Click.setGeometry(QtCore.QRect(160, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_Click.setFont(font)
        self.label_Click.setObjectName("label_Click")
        self.sysMessage = QtWidgets.QPlainTextEdit(editmandialog)
        self.sysMessage.setGeometry(QtCore.QRect(440, 200, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sysMessage.setFont(font)
        self.sysMessage.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sysMessage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sysMessage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sysMessage.setLineWidth(0)
        self.sysMessage.setReadOnly(True)
        self.sysMessage.setObjectName("sysMessage")

        self.retranslateUi(editmandialog)
        QtCore.QMetaObject.connectSlotsByName(editmandialog)
        editmandialog.setTabOrder(self.mantype, self.EditDateTime)
        editmandialog.setTabOrder(self.EditDateTime, self.showorbit)
        editmandialog.setTabOrder(self.showorbit, self.computeFTA)
        editmandialog.setTabOrder(self.computeFTA, self.optimize)
        editmandialog.setTabOrder(self.optimize, self.finish_exec)
        editmandialog.setTabOrder(self.finish_exec, self.finishbutton)
        editmandialog.setTabOrder(self.finishbutton, self.cancelbutton)

    def retranslateUi(self, editmandialog):
        _translate = QtCore.QCoreApplication.translate
        editmandialog.setWindowTitle(_translate("editmandialog", "Maneuver Editor"))
        self.label.setText(_translate("editmandialog", "Type"))
        self.mantype.setToolTip(_translate("editmandialog", "Click and Select a Maneuver type"))
        self.label_time.setText(_translate("editmandialog", "Date&Time"))
        self.label_3.setText(_translate("editmandialog", "ISOT"))
        self.label_4.setText(_translate("editmandialog", "JD"))
        self.label_5.setText(_translate("editmandialog", "Parameters"))
        self.parameters.setToolTip(_translate("editmandialog", "Double Click a Cell to Edit"))
        self.finishbutton.setToolTip(_translate("editmandialog", "Finish editing the Maneuver"))
        self.finishbutton.setText(_translate("editmandialog", "Finish"))
        self.cancelbutton.setToolTip(_translate("editmandialog", "Discard Changes and Quit Editing"))
        self.cancelbutton.setText(_translate("editmandialog", "Cancel"))
        self.showorbit.setToolTip(_translate("editmandialog", "Apply current Parameters"))
        self.showorbit.setText(_translate("editmandialog", "SHOW Orbit"))
        self.computeFTA.setToolTip(_translate("editmandialog", "Invoke FTA Function"))
        self.computeFTA.setText(_translate("editmandialog", "FTA"))
        self.finish_exec.setToolTip(_translate("editmandialog", "Finish Editing and Execute the Maneuver"))
        self.finish_exec.setText(_translate("editmandialog", "Finish and Exec"))
        self.EditDateTime.setToolTip(_translate("editmandialog", "Edit Date & Time"))
        self.EditDateTime.setText(_translate("editmandialog", "Edit Time"))
        self.label_duration.setText(_translate("editmandialog", "Duration (days)"))
        self.optimize.setToolTip(_translate("editmandialog", "Invoke Optimize Assistant"))
        self.optimize.setText(_translate("editmandialog", "OPTIMIZE"))
        self.label_Click.setText(_translate("editmandialog", "Click & Select"))
        self.sysMessage.setToolTip(_translate("editmandialog", "System Messages"))

