# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newflightplandialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewFlightPlanDialog(object):
    def setupUi(self, NewFlightPlanDialog):
        NewFlightPlanDialog.setObjectName("NewFlightPlanDialog")
        NewFlightPlanDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        NewFlightPlanDialog.resize(480, 360)
        NewFlightPlanDialog.setMinimumSize(QtCore.QSize(480, 360))
        NewFlightPlanDialog.setMaximumSize(QtCore.QSize(480, 360))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        NewFlightPlanDialog.setFont(font)
        NewFlightPlanDialog.setModal(True)
        self.probe_box = QtWidgets.QGroupBox(NewFlightPlanDialog)
        self.probe_box.setGeometry(QtCore.QRect(10, 20, 461, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.probe_box.setFont(font)
        self.probe_box.setObjectName("probe_box")
        self.label = QtWidgets.QLabel(self.probe_box)
        self.label.setGeometry(QtCore.QRect(0, 20, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.probe_box)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.probe_box)
        self.label_3.setGeometry(QtCore.QRect(0, 50, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.probename = QtWidgets.QLineEdit(self.probe_box)
        self.probename.setGeometry(QtCore.QRect(80, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.probename.setFont(font)
        self.probename.setObjectName("probename")
        self.spacebase = QtWidgets.QComboBox(self.probe_box)
        self.spacebase.setGeometry(QtCore.QRect(320, 20, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.spacebase.setFont(font)
        self.spacebase.setObjectName("spacebase")
        self.probemass = QtWidgets.QLineEdit(self.probe_box)
        self.probemass.setGeometry(QtCore.QRect(80, 50, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(10)
        self.probemass.setFont(font)
        self.probemass.setObjectName("probemass")
        self.target_box = QtWidgets.QGroupBox(NewFlightPlanDialog)
        self.target_box.setEnabled(True)
        self.target_box.setGeometry(QtCore.QRect(10, 120, 461, 181))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.target_box.setFont(font)
        self.target_box.setFlat(False)
        self.target_box.setObjectName("target_box")
        self.planetbutton = QtWidgets.QRadioButton(self.target_box)
        self.planetbutton.setGeometry(QtCore.QRect(20, 20, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.planetbutton.setFont(font)
        self.planetbutton.setChecked(True)
        self.planetbutton.setObjectName("planetbutton")
        self.smallbodybutton = QtWidgets.QRadioButton(self.target_box)
        self.smallbodybutton.setGeometry(QtCore.QRect(20, 60, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.smallbodybutton.setFont(font)
        self.smallbodybutton.setObjectName("smallbodybutton")
        self.planets = QtWidgets.QComboBox(self.target_box)
        self.planets.setGeometry(QtCore.QRect(110, 20, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.planets.setFont(font)
        self.planets.setObjectName("planets")
        self.targetgroupbox = QtWidgets.QGroupBox(self.target_box)
        self.targetgroupbox.setEnabled(False)
        self.targetgroupbox.setGeometry(QtCore.QRect(110, 60, 341, 111))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.targetgroupbox.setFont(font)
        self.targetgroupbox.setFlat(False)
        self.targetgroupbox.setObjectName("targetgroupbox")
        self.label_5 = QtWidgets.QLabel(self.targetgroupbox)
        self.label_5.setGeometry(QtCore.QRect(2, 20, 69, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.spkfileselect = QtWidgets.QPushButton(self.targetgroupbox)
        self.spkfileselect.setGeometry(QtCore.QRect(290, 15, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.spkfileselect.setFont(font)
        self.spkfileselect.setAutoDefault(False)
        self.spkfileselect.setObjectName("spkfileselect")
        self.targetname = QtWidgets.QLineEdit(self.targetgroupbox)
        self.targetname.setGeometry(QtCore.QRect(80, 80, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.targetname.setFont(font)
        self.targetname.setText("")
        self.targetname.setObjectName("targetname")
        self.label_6 = QtWidgets.QLabel(self.targetgroupbox)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.spkfilepath = QtWidgets.QLineEdit(self.targetgroupbox)
        self.spkfilepath.setGeometry(QtCore.QRect(80, 20, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.spkfilepath.setFont(font)
        self.spkfilepath.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spkfilepath.setFrame(False)
        self.spkfilepath.setReadOnly(True)
        self.spkfilepath.setObjectName("spkfilepath")
        self.label_4 = QtWidgets.QLabel(self.targetgroupbox)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.spkid_list = QtWidgets.QComboBox(self.targetgroupbox)
        self.spkid_list.setGeometry(QtCore.QRect(80, 50, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(10)
        self.spkid_list.setFont(font)
        self.spkid_list.setObjectName("spkid_list")
        self.label_7 = QtWidgets.QLabel(self.targetgroupbox)
        self.label_7.setGeometry(QtCore.QRect(210, 50, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.targetgroupbox)
        self.label_8.setGeometry(QtCore.QRect(210, 80, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.cancelbutton = QtWidgets.QPushButton(NewFlightPlanDialog)
        self.cancelbutton.setGeometry(QtCore.QRect(380, 320, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.cancelbutton.setFont(font)
        self.cancelbutton.setAutoDefault(False)
        self.cancelbutton.setObjectName("cancelbutton")
        self.okbutton = QtWidgets.QPushButton(NewFlightPlanDialog)
        self.okbutton.setGeometry(QtCore.QRect(280, 320, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.okbutton.setFont(font)
        self.okbutton.setAutoDefault(False)
        self.okbutton.setObjectName("okbutton")

        self.retranslateUi(NewFlightPlanDialog)
        self.spacebase.setCurrentIndex(-1)
        self.planets.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(NewFlightPlanDialog)
        NewFlightPlanDialog.setTabOrder(self.probename, self.spacebase)
        NewFlightPlanDialog.setTabOrder(self.spacebase, self.probemass)
        NewFlightPlanDialog.setTabOrder(self.probemass, self.planetbutton)
        NewFlightPlanDialog.setTabOrder(self.planetbutton, self.smallbodybutton)
        NewFlightPlanDialog.setTabOrder(self.smallbodybutton, self.planets)
        NewFlightPlanDialog.setTabOrder(self.planets, self.spkfileselect)
        NewFlightPlanDialog.setTabOrder(self.spkfileselect, self.spkid_list)
        NewFlightPlanDialog.setTabOrder(self.spkid_list, self.targetname)
        NewFlightPlanDialog.setTabOrder(self.targetname, self.okbutton)
        NewFlightPlanDialog.setTabOrder(self.okbutton, self.cancelbutton)

    def retranslateUi(self, NewFlightPlanDialog):
        _translate = QtCore.QCoreApplication.translate
        NewFlightPlanDialog.setWindowTitle(_translate("NewFlightPlanDialog", "New Flight Plan"))
        self.probe_box.setTitle(_translate("NewFlightPlanDialog", "Probe"))
        self.label.setText(_translate("NewFlightPlanDialog", "Name"))
        self.label_2.setText(_translate("NewFlightPlanDialog", "Space Base"))
        self.label_3.setText(_translate("NewFlightPlanDialog", "Mass (kg)"))
        self.probename.setText(_translate("NewFlightPlanDialog", "myprobe"))
        self.probemass.setText(_translate("NewFlightPlanDialog", "500.0"))
        self.target_box.setTitle(_translate("NewFlightPlanDialog", "Target"))
        self.planetbutton.setText(_translate("NewFlightPlanDialog", "Planet"))
        self.smallbodybutton.setText(_translate("NewFlightPlanDialog", "Small Body"))
        self.targetgroupbox.setTitle(_translate("NewFlightPlanDialog", "Properties"))
        self.label_5.setText(_translate("NewFlightPlanDialog", "SPK file"))
        self.spkfileselect.setText(_translate("NewFlightPlanDialog", "Find"))
        self.label_6.setText(_translate("NewFlightPlanDialog", "SPKID"))
        self.label_4.setText(_translate("NewFlightPlanDialog", "Name"))
        self.label_7.setText(_translate("NewFlightPlanDialog", "(Select one)"))
        self.label_8.setText(_translate("NewFlightPlanDialog", "(Enter the name)"))
        self.cancelbutton.setText(_translate("NewFlightPlanDialog", "Cancel"))
        self.okbutton.setText(_translate("NewFlightPlanDialog", "OK"))

