# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editmandialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_editmandialog(object):
    def setupUi(self, editmandialog):
        editmandialog.setObjectName(_fromUtf8("editmandialog"))
        editmandialog.setWindowModality(QtCore.Qt.WindowModal)
        editmandialog.resize(640, 320)
        editmandialog.setModal(True)
        self.label = QtGui.QLabel(editmandialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.mantype = QtGui.QComboBox(editmandialog)
        self.mantype.setGeometry(QtCore.QRect(190, 10, 81, 22))
        self.mantype.setMaxVisibleItems(7)
        self.mantype.setObjectName(_fromUtf8("mantype"))
        self.label_time = QtGui.QLabel(editmandialog)
        self.label_time.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_time.setObjectName(_fromUtf8("label_time"))
        self.isotedit = QtGui.QLineEdit(editmandialog)
        self.isotedit.setGeometry(QtCore.QRect(80, 60, 191, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.isotedit.setFont(font)
        self.isotedit.setObjectName(_fromUtf8("isotedit"))
        self.label_3 = QtGui.QLabel(editmandialog)
        self.label_3.setGeometry(QtCore.QRect(80, 43, 201, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.jdedit = QtGui.QLineEdit(editmandialog)
        self.jdedit.setGeometry(QtCore.QRect(280, 60, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.jdedit.setFont(font)
        self.jdedit.setObjectName(_fromUtf8("jdedit"))
        self.label_4 = QtGui.QLabel(editmandialog)
        self.label_4.setGeometry(QtCore.QRect(330, 44, 31, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(editmandialog)
        self.label_5.setGeometry(QtCore.QRect(100, 90, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.parameters = QtGui.QTableWidget(editmandialog)
        self.parameters.setGeometry(QtCore.QRect(100, 110, 521, 164))
        self.parameters.setCornerButtonEnabled(False)
        self.parameters.setRowCount(8)
        self.parameters.setColumnCount(2)
        self.parameters.setObjectName(_fromUtf8("parameters"))
        self.parameters.horizontalHeader().setVisible(False)
        self.parameters.verticalHeader().setVisible(False)
        self.parameters.verticalHeader().setDefaultSectionSize(20)
        self.parameters.verticalHeader().setMinimumSectionSize(20)
        self.finishbutton = QtGui.QPushButton(editmandialog)
        self.finishbutton.setGeometry(QtCore.QRect(330, 290, 101, 23))
        self.finishbutton.setAutoDefault(False)
        self.finishbutton.setObjectName(_fromUtf8("finishbutton"))
        self.cancelbutton = QtGui.QPushButton(editmandialog)
        self.cancelbutton.setGeometry(QtCore.QRect(540, 290, 75, 23))
        self.cancelbutton.setAutoDefault(False)
        self.cancelbutton.setObjectName(_fromUtf8("cancelbutton"))
        self.showorbit = QtGui.QPushButton(editmandialog)
        self.showorbit.setEnabled(False)
        self.showorbit.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.showorbit.setAutoDefault(False)
        self.showorbit.setObjectName(_fromUtf8("showorbit"))
        self.applymantype = QtGui.QPushButton(editmandialog)
        self.applymantype.setGeometry(QtCore.QRect(274, 9, 41, 23))
        self.applymantype.setAutoDefault(False)
        self.applymantype.setObjectName(_fromUtf8("applymantype"))
        self.mantypedisp = QtGui.QLabel(editmandialog)
        self.mantypedisp.setGeometry(QtCore.QRect(100, 10, 71, 16))
        self.mantypedisp.setText(_fromUtf8(""))
        self.mantypedisp.setObjectName(_fromUtf8("mantypedisp"))
        self.computeFTA = QtGui.QPushButton(editmandialog)
        self.computeFTA.setEnabled(False)
        self.computeFTA.setGeometry(QtCore.QRect(10, 140, 75, 23))
        self.computeFTA.setAutoDefault(False)
        self.computeFTA.setObjectName(_fromUtf8("computeFTA"))
        self.finish_exec = QtGui.QPushButton(editmandialog)
        self.finish_exec.setEnabled(False)
        self.finish_exec.setGeometry(QtCore.QRect(210, 290, 101, 23))
        self.finish_exec.setAutoDefault(False)
        self.finish_exec.setObjectName(_fromUtf8("finish_exec"))
        self.duration = QtGui.QLineEdit(editmandialog)
        self.duration.setEnabled(False)
        self.duration.setGeometry(QtCore.QRect(460, 60, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.duration.setFont(font)
        self.duration.setObjectName(_fromUtf8("duration"))
        self.applyduration = QtGui.QPushButton(editmandialog)
        self.applyduration.setEnabled(False)
        self.applyduration.setGeometry(QtCore.QRect(584, 59, 41, 23))
        self.applyduration.setAutoDefault(False)
        self.applyduration.setObjectName(_fromUtf8("applyduration"))
        self.label_duration = QtGui.QLabel(editmandialog)
        self.label_duration.setEnabled(False)
        self.label_duration.setGeometry(QtCore.QRect(461, 43, 111, 16))
        self.label_duration.setTextFormat(QtCore.Qt.PlainText)
        self.label_duration.setObjectName(_fromUtf8("label_duration"))
        self.optimize = QtGui.QPushButton(editmandialog)
        self.optimize.setEnabled(False)
        self.optimize.setGeometry(QtCore.QRect(10, 170, 75, 23))
        self.optimize.setAutoDefault(False)
        self.optimize.setObjectName(_fromUtf8("optimize"))

        self.retranslateUi(editmandialog)
        QtCore.QMetaObject.connectSlotsByName(editmandialog)
        editmandialog.setTabOrder(self.mantype, self.applymantype)
        editmandialog.setTabOrder(self.applymantype, self.isotedit)
        editmandialog.setTabOrder(self.isotedit, self.jdedit)
        editmandialog.setTabOrder(self.jdedit, self.parameters)
        editmandialog.setTabOrder(self.parameters, self.showorbit)
        editmandialog.setTabOrder(self.showorbit, self.computeFTA)
        editmandialog.setTabOrder(self.computeFTA, self.finish_exec)
        editmandialog.setTabOrder(self.finish_exec, self.finishbutton)
        editmandialog.setTabOrder(self.finishbutton, self.cancelbutton)

    def retranslateUi(self, editmandialog):
        editmandialog.setWindowTitle(_translate("editmandialog", "Maneuver Editor", None))
        self.label.setText(_translate("editmandialog", "Maneuver Type", None))
        self.mantype.setToolTip(_translate("editmandialog", "Select maneuver type and click Apply button", None))
        self.label_time.setText(_translate("editmandialog", "Date&Time", None))
        self.isotedit.setToolTip(_translate("editmandialog", "Date and Time (ISOT format)", None))
        self.label_3.setText(_translate("editmandialog", "ISOT : yyyy-mm-ddThh:mm:ss.ssssss", None))
        self.jdedit.setToolTip(_translate("editmandialog", "Date and Time (Julian day)", None))
        self.label_4.setText(_translate("editmandialog", "JD", None))
        self.label_5.setText(_translate("editmandialog", "Parameters", None))
        self.finishbutton.setToolTip(_translate("editmandialog", "Finish editing", None))
        self.finishbutton.setText(_translate("editmandialog", "Finish", None))
        self.cancelbutton.setToolTip(_translate("editmandialog", "Discard changes and quit editing", None))
        self.cancelbutton.setText(_translate("editmandialog", "Cancel", None))
        self.showorbit.setToolTip(_translate("editmandialog", "Show orbit", None))
        self.showorbit.setText(_translate("editmandialog", "Show Orbit", None))
        self.applymantype.setToolTip(_translate("editmandialog", "Select maneuver type and click Apply button", None))
        self.applymantype.setText(_translate("editmandialog", "Apply", None))
        self.computeFTA.setToolTip(_translate("editmandialog", "Comute fixed time arrival guidance", None))
        self.computeFTA.setText(_translate("editmandialog", "FTA", None))
        self.finish_exec.setToolTip(_translate("editmandialog", "Finish editing and execute this maneuver", None))
        self.finish_exec.setText(_translate("editmandialog", "Finish and Exec", None))
        self.duration.setToolTip(_translate("editmandialog", "Flight Duration for FLYTO", None))
        self.applyduration.setToolTip(_translate("editmandialog", "Apply the flight duration to Date&Time", None))
        self.applyduration.setText(_translate("editmandialog", "Apply", None))
        self.label_duration.setText(_translate("editmandialog", "Flight Duration (days)", None))
        self.optimize.setToolTip(_translate("editmandialog", "Optimize Assistant", None))
        self.optimize.setText(_translate("editmandialog", "Optimize", None))

