# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flightreviewcontrol.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FlightReviewControl(object):
    def setupUi(self, FlightReviewControl):
        FlightReviewControl.setObjectName(_fromUtf8("FlightReviewControl"))
        FlightReviewControl.resize(640, 211)
        self.label = QtGui.QLabel(FlightReviewControl)
        self.label.setGeometry(QtCore.QRect(420, 50, 51, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.delta_t_edit = QtGui.QLineEdit(FlightReviewControl)
        self.delta_t_edit.setGeometry(QtCore.QRect(480, 50, 151, 18))
        self.delta_t_edit.setAcceptDrops(False)
        self.delta_t_edit.setFrame(False)
        self.delta_t_edit.setReadOnly(True)
        self.delta_t_edit.setObjectName(_fromUtf8("delta_t_edit"))
        self.fastbackward = QtGui.QPushButton(FlightReviewControl)
        self.fastbackward.setGeometry(QtCore.QRect(310, 80, 41, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fastbackward.setFont(font)
        self.fastbackward.setAutoRepeat(True)
        self.fastbackward.setAutoDefault(False)
        self.fastbackward.setObjectName(_fromUtf8("fastbackward"))
        self.backward = QtGui.QPushButton(FlightReviewControl)
        self.backward.setGeometry(QtCore.QRect(360, 80, 41, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.backward.setFont(font)
        self.backward.setAutoRepeat(True)
        self.backward.setAutoDefault(False)
        self.backward.setObjectName(_fromUtf8("backward"))
        self.forward = QtGui.QPushButton(FlightReviewControl)
        self.forward.setGeometry(QtCore.QRect(410, 80, 41, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.forward.setFont(font)
        self.forward.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.forward.setAutoRepeat(True)
        self.forward.setAutoDefault(False)
        self.forward.setObjectName(_fromUtf8("forward"))
        self.fastforward = QtGui.QPushButton(FlightReviewControl)
        self.fastforward.setGeometry(QtCore.QRect(460, 80, 41, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fastforward.setFont(font)
        self.fastforward.setAutoRepeat(True)
        self.fastforward.setAutoDefault(False)
        self.fastforward.setObjectName(_fromUtf8("fastforward"))
        self.timescale = QtGui.QSpinBox(FlightReviewControl)
        self.timescale.setGeometry(QtCore.QRect(581, 80, 51, 22))
        self.timescale.setMinimum(2)
        self.timescale.setMaximum(100)
        self.timescale.setSingleStep(1)
        self.timescale.setProperty("value", 10)
        self.timescale.setObjectName(_fromUtf8("timescale"))
        self.label_2 = QtGui.QLabel(FlightReviewControl)
        self.label_2.setGeometry(QtCore.QRect(535, 80, 41, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.showkepler = QtGui.QCheckBox(FlightReviewControl)
        self.showkepler.setGeometry(QtCore.QRect(160, 10, 121, 16))
        self.showkepler.setChecked(False)
        self.showkepler.setObjectName(_fromUtf8("showkepler"))
        self.label_6 = QtGui.QLabel(FlightReviewControl)
        self.label_6.setGeometry(QtCore.QRect(420, 10, 51, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_4 = QtGui.QLabel(FlightReviewControl)
        self.label_4.setGeometry(QtCore.QRect(420, 30, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.starttime = QtGui.QLabel(FlightReviewControl)
        self.starttime.setGeometry(QtCore.QRect(480, 10, 151, 16))
        self.starttime.setText(_fromUtf8(""))
        self.starttime.setObjectName(_fromUtf8("starttime"))
        self.label_3 = QtGui.QLabel(FlightReviewControl)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 161, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_9 = QtGui.QLabel(FlightReviewControl)
        self.label_9.setGeometry(QtCore.QRect(230, 130, 191, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(FlightReviewControl)
        self.label_10.setGeometry(QtCore.QRect(10, 150, 61, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(FlightReviewControl)
        self.label_11.setGeometry(QtCore.QRect(10, 170, 61, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(FlightReviewControl)
        self.label_12.setGeometry(QtCore.QRect(10, 190, 61, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_14 = QtGui.QLabel(FlightReviewControl)
        self.label_14.setGeometry(QtCore.QRect(230, 150, 61, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(FlightReviewControl)
        self.label_15.setGeometry(QtCore.QRect(450, 150, 51, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(FlightReviewControl)
        self.label_16.setGeometry(QtCore.QRect(230, 170, 61, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(FlightReviewControl)
        self.label_17.setGeometry(QtCore.QRect(230, 190, 61, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(FlightReviewControl)
        self.label_18.setGeometry(QtCore.QRect(450, 120, 181, 31))
        self.label_18.setWordWrap(False)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.RPTrange = QtGui.QLabel(FlightReviewControl)
        self.RPTrange.setGeometry(QtCore.QRect(80, 150, 141, 16))
        self.RPTrange.setText(_fromUtf8(""))
        self.RPTrange.setObjectName(_fromUtf8("RPTrange"))
        self.RPTphi = QtGui.QLabel(FlightReviewControl)
        self.RPTphi.setGeometry(QtCore.QRect(80, 170, 141, 16))
        self.RPTphi.setText(_fromUtf8(""))
        self.RPTphi.setObjectName(_fromUtf8("RPTphi"))
        self.RPTelv = QtGui.QLabel(FlightReviewControl)
        self.RPTelv.setGeometry(QtCore.QRect(80, 190, 141, 16))
        self.RPTelv.setText(_fromUtf8(""))
        self.RPTelv.setObjectName(_fromUtf8("RPTelv"))
        self.LoSVvel = QtGui.QLabel(FlightReviewControl)
        self.LoSVvel.setGeometry(QtCore.QRect(510, 150, 121, 16))
        self.LoSVvel.setText(_fromUtf8(""))
        self.LoSVvel.setObjectName(_fromUtf8("LoSVvel"))
        self.label_19 = QtGui.QLabel(FlightReviewControl)
        self.label_19.setGeometry(QtCore.QRect(360, 102, 101, 16))
        self.label_19.setWordWrap(False)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.currenttime = QtGui.QLineEdit(FlightReviewControl)
        self.currenttime.setGeometry(QtCore.QRect(480, 30, 151, 18))
        self.currenttime.setAcceptDrops(False)
        self.currenttime.setFrame(False)
        self.currenttime.setReadOnly(True)
        self.currenttime.setObjectName(_fromUtf8("currenttime"))
        self.RVTvel = QtGui.QLineEdit(FlightReviewControl)
        self.RVTvel.setGeometry(QtCore.QRect(290, 149, 141, 18))
        self.RVTvel.setFrame(False)
        self.RVTvel.setReadOnly(True)
        self.RVTvel.setObjectName(_fromUtf8("RVTvel"))
        self.RVTphi = QtGui.QLineEdit(FlightReviewControl)
        self.RVTphi.setGeometry(QtCore.QRect(290, 169, 141, 18))
        self.RVTphi.setFrame(False)
        self.RVTphi.setReadOnly(True)
        self.RVTphi.setObjectName(_fromUtf8("RVTphi"))
        self.RVTelv = QtGui.QLineEdit(FlightReviewControl)
        self.RVTelv.setGeometry(QtCore.QRect(290, 189, 141, 18))
        self.RVTelv.setFrame(False)
        self.RVTelv.setReadOnly(True)
        self.RVTelv.setObjectName(_fromUtf8("RVTelv"))
        self.groupBox = QtGui.QGroupBox(FlightReviewControl)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 120, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.tobarycenter = QtGui.QRadioButton(self.groupBox)
        self.tobarycenter.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.tobarycenter.setChecked(False)
        self.tobarycenter.setObjectName(_fromUtf8("tobarycenter"))
        self.toprobe = QtGui.QRadioButton(self.groupBox)
        self.toprobe.setGeometry(QtCore.QRect(20, 40, 61, 16))
        self.toprobe.setChecked(True)
        self.toprobe.setObjectName(_fromUtf8("toprobe"))
        self.totarget = QtGui.QRadioButton(self.groupBox)
        self.totarget.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.totarget.setObjectName(_fromUtf8("totarget"))
        self.showplanets = QtGui.QCheckBox(FlightReviewControl)
        self.showplanets.setGeometry(QtCore.QRect(160, 30, 111, 16))
        self.showplanets.setChecked(True)
        self.showplanets.setObjectName(_fromUtf8("showplanets"))
        self.label_2.raise_()
        self.label.raise_()
        self.delta_t_edit.raise_()
        self.fastbackward.raise_()
        self.backward.raise_()
        self.forward.raise_()
        self.fastforward.raise_()
        self.timescale.raise_()
        self.showkepler.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.starttime.raise_()
        self.label_3.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.RPTrange.raise_()
        self.RPTphi.raise_()
        self.RPTelv.raise_()
        self.LoSVvel.raise_()
        self.label_19.raise_()
        self.currenttime.raise_()
        self.RVTvel.raise_()
        self.RVTphi.raise_()
        self.RVTelv.raise_()
        self.groupBox.raise_()
        self.showplanets.raise_()

        self.retranslateUi(FlightReviewControl)
        QtCore.QMetaObject.connectSlotsByName(FlightReviewControl)
        FlightReviewControl.setTabOrder(self.showkepler, self.tobarycenter)
        FlightReviewControl.setTabOrder(self.tobarycenter, self.toprobe)
        FlightReviewControl.setTabOrder(self.toprobe, self.totarget)
        FlightReviewControl.setTabOrder(self.totarget, self.fastbackward)
        FlightReviewControl.setTabOrder(self.fastbackward, self.backward)
        FlightReviewControl.setTabOrder(self.backward, self.forward)
        FlightReviewControl.setTabOrder(self.forward, self.fastforward)
        FlightReviewControl.setTabOrder(self.fastforward, self.currenttime)
        FlightReviewControl.setTabOrder(self.currenttime, self.delta_t_edit)
        FlightReviewControl.setTabOrder(self.delta_t_edit, self.timescale)

    def retranslateUi(self, FlightReviewControl):
        FlightReviewControl.setWindowTitle(_translate("FlightReviewControl", "Flight Review", None))
        self.label.setText(_translate("FlightReviewControl", "DT(days)", None))
        self.delta_t_edit.setToolTip(_translate("FlightReviewControl", "Delta T (you need click apply button)", None))
        self.fastbackward.setToolTip(_translate("FlightReviewControl", "Fast Backword", None))
        self.fastbackward.setText(_translate("FlightReviewControl", "<<", None))
        self.backward.setToolTip(_translate("FlightReviewControl", "Backward", None))
        self.backward.setText(_translate("FlightReviewControl", "<", None))
        self.forward.setToolTip(_translate("FlightReviewControl", "Forward", None))
        self.forward.setText(_translate("FlightReviewControl", ">", None))
        self.fastforward.setToolTip(_translate("FlightReviewControl", "Fast Forward", None))
        self.fastforward.setText(_translate("FlightReviewControl", ">>", None))
        self.timescale.setToolTip(_translate("FlightReviewControl", "Select powers", None))
        self.label_2.setText(_translate("FlightReviewControl", "Hopping", None))
        self.showkepler.setText(_translate("FlightReviewControl", "Show Kepler Orbit", None))
        self.label_6.setText(_translate("FlightReviewControl", "S. Time", None))
        self.label_4.setText(_translate("FlightReviewControl", "C. Time", None))
        self.label_3.setText(_translate("FlightReviewControl", "Relative Position of Target", None))
        self.label_9.setText(_translate("FlightReviewControl", "Relative Velocity of Target", None))
        self.label_10.setText(_translate("FlightReviewControl", "range (km)", None))
        self.label_11.setText(_translate("FlightReviewControl", "phi (deg)", None))
        self.label_12.setText(_translate("FlightReviewControl", "elv (deg)", None))
        self.label_14.setText(_translate("FlightReviewControl", "vel (m/s)", None))
        self.label_15.setText(_translate("FlightReviewControl", "vel (m/s)", None))
        self.label_16.setText(_translate("FlightReviewControl", "phi (deg)", None))
        self.label_17.setText(_translate("FlightReviewControl", "elv (deg)", None))
        self.label_18.setText(_translate("FlightReviewControl", "Line of Sight Velocity (departing)", None))
        self.label_19.setText(_translate("FlightReviewControl", "Time Manipulator", None))
        self.currenttime.setToolTip(_translate("FlightReviewControl", "Prediction Time (Copiable)", None))
        self.RVTvel.setToolTip(_translate("FlightReviewControl", "Relative Velocity abs. (Copiable)", None))
        self.RVTphi.setToolTip(_translate("FlightReviewControl", "Relative Velocity phi (Copiable)", None))
        self.RVTelv.setToolTip(_translate("FlightReviewControl", "Relative Velocity elv (Copiable)", None))
        self.groupBox.setTitle(_translate("FlightReviewControl", "Look at", None))
        self.tobarycenter.setText(_translate("FlightReviewControl", "SSB", None))
        self.toprobe.setText(_translate("FlightReviewControl", "Probe", None))
        self.totarget.setText(_translate("FlightReviewControl", "Target", None))
        self.showplanets.setText(_translate("FlightReviewControl", "Show Planets", None))

