# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ftasettingdialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ftasettingdialog(object):
    def setupUi(self, ftasettingdialog):
        ftasettingdialog.setObjectName(_fromUtf8("ftasettingdialog"))
        ftasettingdialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ftasettingdialog.resize(480, 480)
        ftasettingdialog.setModal(True)
        self.groupBox = QtGui.QGroupBox(ftasettingdialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 441, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.fromshoworbit = QtGui.QRadioButton(self.groupBox)
        self.fromshoworbit.setGeometry(QtCore.QRect(30, 20, 391, 16))
        self.fromshoworbit.setChecked(True)
        self.fromshoworbit.setObjectName(_fromUtf8("fromshoworbit"))
        self.directinput = QtGui.QRadioButton(self.groupBox)
        self.directinput.setGeometry(QtCore.QRect(30, 40, 391, 16))
        self.directinput.setObjectName(_fromUtf8("directinput"))
        self.timetoarrival = QtGui.QLineEdit(self.groupBox)
        self.timetoarrival.setEnabled(False)
        self.timetoarrival.setGeometry(QtCore.QRect(310, 60, 113, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.timetoarrival.setFont(font)
        self.timetoarrival.setCursorPosition(0)
        self.timetoarrival.setObjectName(_fromUtf8("timetoarrival"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(190, 60, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.OLcoords = QtGui.QGroupBox(ftasettingdialog)
        self.OLcoords.setEnabled(False)
        self.OLcoords.setGeometry(QtCore.QRect(20, 320, 441, 91))
        self.OLcoords.setObjectName(_fromUtf8("OLcoords"))
        self.label_2 = QtGui.QLabel(self.OLcoords)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 181, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.OLcoords)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 181, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.OLcoords)
        self.label_4.setGeometry(QtCore.QRect(30, 60, 181, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.rangeedit = QtGui.QLineEdit(self.OLcoords)
        self.rangeedit.setGeometry(QtCore.QRect(230, 20, 91, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.rangeedit.setFont(font)
        self.rangeedit.setObjectName(_fromUtf8("rangeedit"))
        self.phiedit = QtGui.QLineEdit(self.OLcoords)
        self.phiedit.setGeometry(QtCore.QRect(230, 40, 91, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.phiedit.setFont(font)
        self.phiedit.setObjectName(_fromUtf8("phiedit"))
        self.elvedit = QtGui.QLineEdit(self.OLcoords)
        self.elvedit.setGeometry(QtCore.QRect(230, 60, 91, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.elvedit.setFont(font)
        self.elvedit.setObjectName(_fromUtf8("elvedit"))
        self.cancel_button = QtGui.QPushButton(ftasettingdialog)
        self.cancel_button.setGeometry(QtCore.QRect(380, 440, 75, 23))
        self.cancel_button.setAutoDefault(False)
        self.cancel_button.setObjectName(_fromUtf8("cancel_button"))
        self.ok_button = QtGui.QPushButton(ftasettingdialog)
        self.ok_button.setGeometry(QtCore.QRect(290, 440, 75, 23))
        self.ok_button.setAutoDefault(False)
        self.ok_button.setObjectName(_fromUtf8("ok_button"))
        self.groupBox_3 = QtGui.QGroupBox(ftasettingdialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 120, 441, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.selTargetcenter = QtGui.QRadioButton(self.groupBox_3)
        self.selTargetcenter.setGeometry(QtCore.QRect(30, 20, 391, 16))
        self.selTargetcenter.setChecked(True)
        self.selTargetcenter.setObjectName(_fromUtf8("selTargetcenter"))
        self.selBplanecoord = QtGui.QRadioButton(self.groupBox_3)
        self.selBplanecoord.setGeometry(QtCore.QRect(30, 40, 391, 16))
        self.selBplanecoord.setObjectName(_fromUtf8("selBplanecoord"))
        self.selOLcoord = QtGui.QRadioButton(self.groupBox_3)
        self.selOLcoord.setGeometry(QtCore.QRect(30, 60, 391, 16))
        self.selOLcoord.setObjectName(_fromUtf8("selOLcoord"))
        self.Bplanecoords = QtGui.QGroupBox(ftasettingdialog)
        self.Bplanecoords.setEnabled(False)
        self.Bplanecoords.setGeometry(QtCore.QRect(20, 230, 441, 71))
        self.Bplanecoords.setObjectName(_fromUtf8("Bplanecoords"))
        self.label_5 = QtGui.QLabel(self.Bplanecoords)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 181, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.Brangeedit = QtGui.QLineEdit(self.Bplanecoords)
        self.Brangeedit.setGeometry(QtCore.QRect(230, 20, 91, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.Brangeedit.setFont(font)
        self.Brangeedit.setObjectName(_fromUtf8("Brangeedit"))
        self.label_6 = QtGui.QLabel(self.Bplanecoords)
        self.label_6.setGeometry(QtCore.QRect(30, 40, 181, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.betaedit = QtGui.QLineEdit(self.Bplanecoords)
        self.betaedit.setGeometry(QtCore.QRect(230, 40, 91, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.betaedit.setFont(font)
        self.betaedit.setObjectName(_fromUtf8("betaedit"))

        self.retranslateUi(ftasettingdialog)
        QtCore.QMetaObject.connectSlotsByName(ftasettingdialog)

    def retranslateUi(self, ftasettingdialog):
        ftasettingdialog.setWindowTitle(_translate("ftasettingdialog", "FTA Setting", None))
        self.groupBox.setTitle(_translate("ftasettingdialog", "Time to Arrival : ", None))
        self.fromshoworbit.setText(_translate("ftasettingdialog", "Get DT of Show Orbit window", None))
        self.directinput.setText(_translate("ftasettingdialog", "Specify Time to Arrival", None))
        self.timetoarrival.setText(_translate("ftasettingdialog", "100.00000", None))
        self.label.setText(_translate("ftasettingdialog", "Time to Arrival (days)", None))
        self.OLcoords.setTitle(_translate("ftasettingdialog", "Orbit Local Coordinates", None))
        self.label_2.setText(_translate("ftasettingdialog", "Range from Target Center (km)", None))
        self.label_3.setText(_translate("ftasettingdialog", "phi (deg)", None))
        self.label_4.setText(_translate("ftasettingdialog", "elv (deg)", None))
        self.rangeedit.setText(_translate("ftasettingdialog", "0.0", None))
        self.phiedit.setToolTip(_translate("ftasettingdialog", "Angle phi on Orbit Local coordinate", None))
        self.phiedit.setText(_translate("ftasettingdialog", "0.0", None))
        self.elvedit.setToolTip(_translate("ftasettingdialog", "Angle elv on Orbit Local coordinate", None))
        self.elvedit.setText(_translate("ftasettingdialog", "0.0", None))
        self.cancel_button.setText(_translate("ftasettingdialog", "Cancel", None))
        self.ok_button.setText(_translate("ftasettingdialog", "OK", None))
        self.groupBox_3.setTitle(_translate("ftasettingdialog", "Precise Targeting", None))
        self.selTargetcenter.setText(_translate("ftasettingdialog", "Center of Target", None))
        self.selBplanecoord.setText(_translate("ftasettingdialog", "Specify with B-plane coordinates (range and beta)", None))
        self.selOLcoord.setText(_translate("ftasettingdialog", "Specify with Orbit Local coordinates (range, phi, and elv)", None))
        self.Bplanecoords.setTitle(_translate("ftasettingdialog", "B-plane coordinates", None))
        self.label_5.setText(_translate("ftasettingdialog", "Range from Target Center (km)", None))
        self.Brangeedit.setText(_translate("ftasettingdialog", "0.0", None))
        self.label_6.setText(_translate("ftasettingdialog", "beta (deg)", None))
        self.betaedit.setToolTip(_translate("ftasettingdialog", "Angle beta on B-plane", None))
        self.betaedit.setText(_translate("ftasettingdialog", "0.0", None))

