# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 700)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.manplans = QtGui.QTableWidget(self.centralwidget)
        self.manplans.setEnabled(False)
        self.manplans.setGeometry(QtCore.QRect(10, 70, 521, 251))
        self.manplans.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.manplans.setTabKeyNavigation(False)
        self.manplans.setProperty("showDropIndicator", False)
        self.manplans.setDragDropOverwriteMode(False)
        self.manplans.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.manplans.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.manplans.setCornerButtonEnabled(False)
        self.manplans.setRowCount(10)
        self.manplans.setColumnCount(3)
        self.manplans.setObjectName(_fromUtf8("manplans"))
        item = QtGui.QTableWidgetItem()
        self.manplans.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.manplans.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.manplans.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.manplans.setItem(0, 0, item)
        self.manplans.horizontalHeader().setVisible(True)
        self.manplans.horizontalHeader().setCascadingSectionResizes(True)
        self.manplans.horizontalHeader().setDefaultSectionSize(100)
        self.manplans.horizontalHeader().setHighlightSections(False)
        self.manplans.verticalHeader().setVisible(True)
        self.manplans.verticalHeader().setDefaultSectionSize(20)
        self.manplans.verticalHeader().setHighlightSections(False)
        self.manplans.verticalHeader().setMinimumSectionSize(20)
        self.execNext = QtGui.QPushButton(self.centralwidget)
        self.execNext.setEnabled(False)
        self.execNext.setGeometry(QtCore.QRect(550, 70, 75, 23))
        self.execNext.setObjectName(_fromUtf8("execNext"))
        self.insertMan = QtGui.QPushButton(self.centralwidget)
        self.insertMan.setEnabled(False)
        self.insertMan.setGeometry(QtCore.QRect(550, 270, 75, 23))
        self.insertMan.setStatusTip(_fromUtf8(""))
        self.insertMan.setWhatsThis(_fromUtf8(""))
        self.insertMan.setObjectName(_fromUtf8("insertMan"))
        self.showOrbit = QtGui.QPushButton(self.centralwidget)
        self.showOrbit.setEnabled(False)
        self.showOrbit.setGeometry(QtCore.QRect(534, 10, 91, 23))
        self.showOrbit.setObjectName(_fromUtf8("showOrbit"))
        self.editMan = QtGui.QPushButton(self.centralwidget)
        self.editMan.setEnabled(False)
        self.editMan.setGeometry(QtCore.QRect(550, 240, 75, 23))
        self.editMan.setObjectName(_fromUtf8("editMan"))
        self.execto = QtGui.QPushButton(self.centralwidget)
        self.execto.setEnabled(False)
        self.execto.setGeometry(QtCore.QRect(550, 100, 75, 23))
        self.execto.setObjectName(_fromUtf8("execto"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.probename = QtGui.QLabel(self.centralwidget)
        self.probename.setGeometry(QtCore.QRect(90, 10, 231, 16))
        self.probename.setText(_fromUtf8(""))
        self.probename.setObjectName(_fromUtf8("probename"))
        self.targetname = QtGui.QLabel(self.centralwidget)
        self.targetname.setGeometry(QtCore.QRect(90, 30, 231, 16))
        self.targetname.setText(_fromUtf8(""))
        self.targetname.setObjectName(_fromUtf8("targetname"))
        self.deleteMan = QtGui.QPushButton(self.centralwidget)
        self.deleteMan.setEnabled(False)
        self.deleteMan.setGeometry(QtCore.QRect(550, 300, 75, 23))
        self.deleteMan.setStatusTip(_fromUtf8(""))
        self.deleteMan.setObjectName(_fromUtf8("deleteMan"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.manfilename = QtGui.QLabel(self.centralwidget)
        self.manfilename.setGeometry(QtCore.QRect(90, 50, 231, 16))
        self.manfilename.setText(_fromUtf8(""))
        self.manfilename.setObjectName(_fromUtf8("manfilename"))
        self.editnext = QtGui.QPushButton(self.centralwidget)
        self.editnext.setEnabled(False)
        self.editnext.setGeometry(QtCore.QRect(550, 210, 75, 23))
        self.editnext.setObjectName(_fromUtf8("editnext"))
        self.initexec = QtGui.QPushButton(self.centralwidget)
        self.initexec.setEnabled(False)
        self.initexec.setGeometry(QtCore.QRect(550, 150, 75, 23))
        self.initexec.setObjectName(_fromUtf8("initexec"))
        self.redrawtargetorb = QtGui.QPushButton(self.centralwidget)
        self.redrawtargetorb.setEnabled(False)
        self.redrawtargetorb.setGeometry(QtCore.QRect(290, 10, 121, 23))
        self.redrawtargetorb.setObjectName(_fromUtf8("redrawtargetorb"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 360, 131, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 380, 131, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 340, 131, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 440, 131, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 480, 131, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 500, 131, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 520, 131, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 540, 131, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 600, 131, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 620, 131, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_ELM = QtGui.QLabel(self.centralwidget)
        self.label_ELM.setGeometry(QtCore.QRect(180, 340, 181, 16))
        self.label_ELM.setText(_fromUtf8(""))
        self.label_ELM.setObjectName(_fromUtf8("label_ELM"))
        self.label_ISOT = QtGui.QLabel(self.centralwidget)
        self.label_ISOT.setGeometry(QtCore.QRect(180, 360, 181, 16))
        self.label_ISOT.setText(_fromUtf8(""))
        self.label_ISOT.setObjectName(_fromUtf8("label_ISOT"))
        self.label_JD = QtGui.QLabel(self.centralwidget)
        self.label_JD.setGeometry(QtCore.QRect(180, 380, 181, 16))
        self.label_JD.setText(_fromUtf8(""))
        self.label_JD.setObjectName(_fromUtf8("label_JD"))
        self.label_SMA = QtGui.QLabel(self.centralwidget)
        self.label_SMA.setGeometry(QtCore.QRect(180, 440, 181, 16))
        self.label_SMA.setText(_fromUtf8(""))
        self.label_SMA.setObjectName(_fromUtf8("label_SMA"))
        self.label_Ecc = QtGui.QLabel(self.centralwidget)
        self.label_Ecc.setGeometry(QtCore.QRect(180, 480, 181, 16))
        self.label_Ecc.setText(_fromUtf8(""))
        self.label_Ecc.setObjectName(_fromUtf8("label_Ecc"))
        self.label_Inc = QtGui.QLabel(self.centralwidget)
        self.label_Inc.setGeometry(QtCore.QRect(180, 500, 181, 16))
        self.label_Inc.setText(_fromUtf8(""))
        self.label_Inc.setObjectName(_fromUtf8("label_Inc"))
        self.label_LAN = QtGui.QLabel(self.centralwidget)
        self.label_LAN.setGeometry(QtCore.QRect(180, 520, 181, 16))
        self.label_LAN.setText(_fromUtf8(""))
        self.label_LAN.setObjectName(_fromUtf8("label_LAN"))
        self.label_APH = QtGui.QLabel(self.centralwidget)
        self.label_APH.setGeometry(QtCore.QRect(180, 540, 181, 16))
        self.label_APH.setText(_fromUtf8(""))
        self.label_APH.setObjectName(_fromUtf8("label_APH"))
        self.label_MA = QtGui.QLabel(self.centralwidget)
        self.label_MA.setGeometry(QtCore.QRect(180, 600, 181, 16))
        self.label_MA.setText(_fromUtf8(""))
        self.label_MA.setObjectName(_fromUtf8("label_MA"))
        self.label_OP = QtGui.QLabel(self.centralwidget)
        self.label_OP.setGeometry(QtCore.QRect(180, 620, 181, 16))
        self.label_OP.setText(_fromUtf8(""))
        self.label_OP.setObjectName(_fromUtf8("label_OP"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 560, 131, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 580, 131, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_PPT = QtGui.QLabel(self.centralwidget)
        self.label_PPT.setGeometry(QtCore.QRect(180, 560, 181, 16))
        self.label_PPT.setText(_fromUtf8(""))
        self.label_PPT.setObjectName(_fromUtf8("label_PPT"))
        self.label_PPTJD = QtGui.QLabel(self.centralwidget)
        self.label_PPTJD.setGeometry(QtCore.QRect(180, 580, 181, 16))
        self.label_PPTJD.setText(_fromUtf8(""))
        self.label_PPTJD.setObjectName(_fromUtf8("label_PPTJD"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 460, 131, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_SMAAU = QtGui.QLabel(self.centralwidget)
        self.label_SMAAU.setGeometry(QtCore.QRect(180, 460, 181, 16))
        self.label_SMAAU.setText(_fromUtf8(""))
        self.label_SMAAU.setObjectName(_fromUtf8("label_SMAAU"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 400, 141, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 420, 151, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_range = QtGui.QLabel(self.centralwidget)
        self.label_range.setGeometry(QtCore.QRect(180, 400, 181, 16))
        self.label_range.setText(_fromUtf8(""))
        self.label_range.setObjectName(_fromUtf8("label_range"))
        self.label_velocity = QtGui.QLabel(self.centralwidget)
        self.label_velocity.setGeometry(QtCore.QRect(180, 420, 181, 16))
        self.label_velocity.setText(_fromUtf8(""))
        self.label_velocity.setObjectName(_fromUtf8("label_velocity"))
        self.flightreview = QtGui.QPushButton(self.centralwidget)
        self.flightreview.setEnabled(False)
        self.flightreview.setGeometry(QtCore.QRect(430, 10, 91, 23))
        self.flightreview.setObjectName(_fromUtf8("flightreview"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setEnabled(False)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNew_from_current_status = QtGui.QAction(MainWindow)
        self.actionNew_from_current_status.setEnabled(False)
        self.actionNew_from_current_status.setObjectName(_fromUtf8("actionNew_from_current_status"))
        self.actionAbout_SSVG = QtGui.QAction(MainWindow)
        self.actionAbout_SSVG.setObjectName(_fromUtf8("actionAbout_SSVG"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_SSVG)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.manplans, self.showOrbit)
        MainWindow.setTabOrder(self.showOrbit, self.execNext)
        MainWindow.setTabOrder(self.execNext, self.execto)
        MainWindow.setTabOrder(self.execto, self.editMan)
        MainWindow.setTabOrder(self.editMan, self.insertMan)
        MainWindow.setTabOrder(self.insertMan, self.deleteMan)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SSVG", None))
        item = self.manplans.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.manplans.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Parameters", None))
        item = self.manplans.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Exec", None))
        __sortingEnabled = self.manplans.isSortingEnabled()
        self.manplans.setSortingEnabled(False)
        self.manplans.setSortingEnabled(__sortingEnabled)
        self.execNext.setToolTip(_translate("MainWindow", "Execute \'Next\' maneuver", None))
        self.execNext.setText(_translate("MainWindow", "Exec Next", None))
        self.insertMan.setToolTip(_translate("MainWindow", "Insert a blank maneuver", None))
        self.insertMan.setText(_translate("MainWindow", "Insert *", None))
        self.showOrbit.setToolTip(_translate("MainWindow", "Draw position and orbit", None))
        self.showOrbit.setText(_translate("MainWindow", "Show Orbit", None))
        self.editMan.setToolTip(_translate("MainWindow", "Edit selected maneuver", None))
        self.editMan.setText(_translate("MainWindow", "Edit *", None))
        self.execto.setToolTip(_translate("MainWindow", "Execute maneuvers until selected one", None))
        self.execto.setText(_translate("MainWindow", "Exec to *", None))
        self.label.setText(_translate("MainWindow", "Probe Name : ", None))
        self.label_2.setText(_translate("MainWindow", "Target        :", None))
        self.deleteMan.setToolTip(_translate("MainWindow", "Delete selected maneuver", None))
        self.deleteMan.setText(_translate("MainWindow", "Delete *", None))
        self.label_3.setText(_translate("MainWindow", "Plan File     :", None))
        self.editnext.setToolTip(_translate("MainWindow", "Edit \'Next\' maneuver", None))
        self.editnext.setText(_translate("MainWindow", "Edit Next", None))
        self.initexec.setToolTip(_translate("MainWindow", "Initialize execution of the flight plan", None))
        self.initexec.setText(_translate("MainWindow", "Ex Initialize", None))
        self.redrawtargetorb.setToolTip(_translate("MainWindow", "Redraw Target Orbit Line", None))
        self.redrawtargetorb.setText(_translate("MainWindow", "Redraw Target Orbit", None))
        self.label_4.setText(_translate("MainWindow", "Current Time", None))
        self.label_5.setText(_translate("MainWindow", "Current Time (JD)", None))
        self.label_6.setText(_translate("MainWindow", "Executed Last  Maneuver", None))
        self.label_7.setText(_translate("MainWindow", "Semi-major Axis (km)", None))
        self.label_8.setText(_translate("MainWindow", "Eccentricity", None))
        self.label_9.setText(_translate("MainWindow", "Inclination (deg)", None))
        self.label_10.setText(_translate("MainWindow", "Long. of Asc. Node (deg)", None))
        self.label_11.setText(_translate("MainWindow", "Arg. of Perihelion (deg)", None))
        self.label_12.setText(_translate("MainWindow", "Mean Anomary (deg)", None))
        self.label_13.setText(_translate("MainWindow", "Orbital Period (days)", None))
        self.label_14.setText(_translate("MainWindow", "Perihelion Passage", None))
        self.label_15.setText(_translate("MainWindow", "Perihelion Passage (JD)", None))
        self.label_16.setText(_translate("MainWindow", "Semi-major Axis (AU)", None))
        self.label_17.setText(_translate("MainWindow", "Range from the Sun (km)", None))
        self.label_18.setText(_translate("MainWindow", "Velocity rel. to the Sun (m/s)", None))
        self.flightreview.setToolTip(_translate("MainWindow", "Review FLYTO maneuver", None))
        self.flightreview.setText(_translate("MainWindow", "Flight Review", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open", None))
        self.actionNew.setText(_translate("MainWindow", "&New", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save &As...", None))
        self.actionQuit.setText(_translate("MainWindow", "&Quit", None))
        self.actionNew_from_current_status.setText(_translate("MainWindow", "New from current status", None))
        self.actionAbout_SSVG.setText(_translate("MainWindow", "about SSVG", None))

