# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newflightplandialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NewFlightPlanDialog(object):
    def setupUi(self, NewFlightPlanDialog):
        NewFlightPlanDialog.setObjectName(_fromUtf8("NewFlightPlanDialog"))
        NewFlightPlanDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        NewFlightPlanDialog.resize(480, 640)
        NewFlightPlanDialog.setModal(True)
        self.groupBox = QtGui.QGroupBox(NewFlightPlanDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 461, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 51, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(250, 50, 61, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.probename = QtGui.QLineEdit(self.groupBox)
        self.probename.setGeometry(QtCore.QRect(80, 20, 111, 20))
        self.probename.setObjectName(_fromUtf8("probename"))
        self.spacebase = QtGui.QComboBox(self.groupBox)
        self.spacebase.setGeometry(QtCore.QRect(320, 50, 111, 22))
        self.spacebase.setObjectName(_fromUtf8("spacebase"))
        self.probemass = QtGui.QLineEdit(self.groupBox)
        self.probemass.setGeometry(QtCore.QRect(80, 50, 113, 20))
        self.probemass.setObjectName(_fromUtf8("probemass"))
        self.startfromspacebase = QtGui.QCheckBox(self.groupBox)
        self.startfromspacebase.setEnabled(False)
        self.startfromspacebase.setGeometry(QtCore.QRect(250, 20, 161, 16))
        self.startfromspacebase.setChecked(True)
        self.startfromspacebase.setObjectName(_fromUtf8("startfromspacebase"))
        self.groupBox_2 = QtGui.QGroupBox(NewFlightPlanDialog)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 461, 131))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.planetbutton = QtGui.QRadioButton(self.groupBox_2)
        self.planetbutton.setGeometry(QtCore.QRect(20, 30, 91, 16))
        self.planetbutton.setChecked(True)
        self.planetbutton.setObjectName(_fromUtf8("planetbutton"))
        self.smallbodybutton = QtGui.QRadioButton(self.groupBox_2)
        self.smallbodybutton.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.smallbodybutton.setObjectName(_fromUtf8("smallbodybutton"))
        self.planets = QtGui.QComboBox(self.groupBox_2)
        self.planets.setGeometry(QtCore.QRect(20, 90, 111, 22))
        self.planets.setObjectName(_fromUtf8("planets"))
        self.targetgroupbox = QtGui.QGroupBox(self.groupBox_2)
        self.targetgroupbox.setEnabled(False)
        self.targetgroupbox.setGeometry(QtCore.QRect(150, 20, 301, 101))
        self.targetgroupbox.setTitle(_fromUtf8(""))
        self.targetgroupbox.setFlat(False)
        self.targetgroupbox.setObjectName(_fromUtf8("targetgroupbox"))
        self.spkid_edit = QtGui.QLineEdit(self.targetgroupbox)
        self.spkid_edit.setGeometry(QtCore.QRect(60, 70, 113, 20))
        self.spkid_edit.setObjectName(_fromUtf8("spkid_edit"))
        self.label_5 = QtGui.QLabel(self.targetgroupbox)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.spkfileselect = QtGui.QPushButton(self.targetgroupbox)
        self.spkfileselect.setGeometry(QtCore.QRect(272, 38, 21, 23))
        self.spkfileselect.setAutoDefault(False)
        self.spkfileselect.setObjectName(_fromUtf8("spkfileselect"))
        self.targetname = QtGui.QLineEdit(self.targetgroupbox)
        self.targetname.setGeometry(QtCore.QRect(60, 10, 113, 20))
        self.targetname.setObjectName(_fromUtf8("targetname"))
        self.label_6 = QtGui.QLabel(self.targetgroupbox)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 41, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.spkfilepath = QtGui.QLineEdit(self.targetgroupbox)
        self.spkfilepath.setGeometry(QtCore.QRect(60, 40, 211, 20))
        self.spkfilepath.setObjectName(_fromUtf8("spkfilepath"))
        self.label_4 = QtGui.QLabel(self.targetgroupbox)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.startparametersgroupbox = QtGui.QGroupBox(NewFlightPlanDialog)
        self.startparametersgroupbox.setEnabled(False)
        self.startparametersgroupbox.setGeometry(QtCore.QRect(10, 280, 461, 301))
        self.startparametersgroupbox.setObjectName(_fromUtf8("startparametersgroupbox"))
        self.label_7 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_8.setGeometry(QtCore.QRect(110, 14, 171, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_9.setGeometry(QtCore.QRect(310, 14, 61, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.isot_edit = QtGui.QLineEdit(self.startparametersgroupbox)
        self.isot_edit.setGeometry(QtCore.QRect(110, 30, 171, 20))
        self.isot_edit.setObjectName(_fromUtf8("isot_edit"))
        self.jd_edit = QtGui.QLineEdit(self.startparametersgroupbox)
        self.jd_edit.setGeometry(QtCore.QRect(300, 30, 131, 20))
        self.jd_edit.setObjectName(_fromUtf8("jd_edit"))
        self.label_10 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 51, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_11.setGeometry(QtCore.QRect(110, 70, 21, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_12.setGeometry(QtCore.QRect(110, 100, 21, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_13.setGeometry(QtCore.QRect(110, 130, 21, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.x_edit = QtGui.QLineEdit(self.startparametersgroupbox)
        self.x_edit.setGeometry(QtCore.QRect(130, 70, 151, 20))
        self.x_edit.setObjectName(_fromUtf8("x_edit"))
        self.y_edit = QtGui.QLineEdit(self.startparametersgroupbox)
        self.y_edit.setGeometry(QtCore.QRect(130, 100, 151, 20))
        self.y_edit.setObjectName(_fromUtf8("y_edit"))
        self.z_edit = QtGui.QLineEdit(self.startparametersgroupbox)
        self.z_edit.setGeometry(QtCore.QRect(130, 130, 151, 20))
        self.z_edit.setObjectName(_fromUtf8("z_edit"))
        self.label_14 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_14.setGeometry(QtCore.QRect(20, 170, 61, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_15.setGeometry(QtCore.QRect(110, 170, 21, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_16.setGeometry(QtCore.QRect(110, 200, 21, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_17.setGeometry(QtCore.QRect(110, 230, 21, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.xd_edit = QtGui.QLineEdit(self.startparametersgroupbox)
        self.xd_edit.setGeometry(QtCore.QRect(130, 170, 151, 20))
        self.xd_edit.setObjectName(_fromUtf8("xd_edit"))
        self.yd_edit = QtGui.QLineEdit(self.startparametersgroupbox)
        self.yd_edit.setGeometry(QtCore.QRect(130, 200, 151, 20))
        self.yd_edit.setObjectName(_fromUtf8("yd_edit"))
        self.zd_edit = QtGui.QLineEdit(self.startparametersgroupbox)
        self.zd_edit.setGeometry(QtCore.QRect(130, 230, 151, 20))
        self.zd_edit.setObjectName(_fromUtf8("zd_edit"))
        self.label_18 = QtGui.QLabel(self.startparametersgroupbox)
        self.label_18.setGeometry(QtCore.QRect(20, 260, 421, 31))
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.cancelbutton = QtGui.QPushButton(NewFlightPlanDialog)
        self.cancelbutton.setGeometry(QtCore.QRect(380, 600, 75, 23))
        self.cancelbutton.setAutoDefault(False)
        self.cancelbutton.setObjectName(_fromUtf8("cancelbutton"))
        self.okbutton = QtGui.QPushButton(NewFlightPlanDialog)
        self.okbutton.setGeometry(QtCore.QRect(280, 600, 75, 23))
        self.okbutton.setObjectName(_fromUtf8("okbutton"))

        self.retranslateUi(NewFlightPlanDialog)
        self.spacebase.setCurrentIndex(-1)
        self.planets.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(NewFlightPlanDialog)

    def retranslateUi(self, NewFlightPlanDialog):
        NewFlightPlanDialog.setWindowTitle(_translate("NewFlightPlanDialog", "New Flight Plan", None))
        self.groupBox.setTitle(_translate("NewFlightPlanDialog", "Probe properties", None))
        self.label.setText(_translate("NewFlightPlanDialog", "Name", None))
        self.label_2.setText(_translate("NewFlightPlanDialog", "Space Base", None))
        self.label_3.setText(_translate("NewFlightPlanDialog", "Mass (kg)", None))
        self.probename.setText(_translate("NewFlightPlanDialog", "myprobe", None))
        self.probemass.setText(_translate("NewFlightPlanDialog", "500.0", None))
        self.startfromspacebase.setText(_translate("NewFlightPlanDialog", "Start from a Space Base", None))
        self.groupBox_2.setTitle(_translate("NewFlightPlanDialog", "Target", None))
        self.planetbutton.setText(_translate("NewFlightPlanDialog", "Planet/Moon", None))
        self.smallbodybutton.setText(_translate("NewFlightPlanDialog", "Small Body", None))
        self.spkid_edit.setText(_translate("NewFlightPlanDialog", "2000001", None))
        self.label_5.setText(_translate("NewFlightPlanDialog", "SPK file", None))
        self.spkfileselect.setText(_translate("NewFlightPlanDialog", "...", None))
        self.targetname.setText(_translate("NewFlightPlanDialog", "Ceres", None))
        self.label_6.setText(_translate("NewFlightPlanDialog", "SPKID", None))
        self.label_4.setText(_translate("NewFlightPlanDialog", "Name", None))
        self.startparametersgroupbox.setTitle(_translate("NewFlightPlanDialog", "Start Parameters", None))
        self.label_7.setText(_translate("NewFlightPlanDialog", "Start Time", None))
        self.label_8.setText(_translate("NewFlightPlanDialog", "ISOT: yyyy-mm-ddThh:mm:ss.sss", None))
        self.label_9.setText(_translate("NewFlightPlanDialog", "JD", None))
        self.isot_edit.setText(_translate("NewFlightPlanDialog", "2001-01-01T00:00:00.000", None))
        self.jd_edit.setText(_translate("NewFlightPlanDialog", "2451910.5", None))
        self.label_10.setText(_translate("NewFlightPlanDialog", "Position", None))
        self.label_11.setText(_translate("NewFlightPlanDialog", "X", None))
        self.label_12.setText(_translate("NewFlightPlanDialog", "Y", None))
        self.label_13.setText(_translate("NewFlightPlanDialog", "Z", None))
        self.x_edit.setText(_translate("NewFlightPlanDialog", "0.0", None))
        self.y_edit.setText(_translate("NewFlightPlanDialog", "0.0", None))
        self.z_edit.setText(_translate("NewFlightPlanDialog", "0.0", None))
        self.label_14.setText(_translate("NewFlightPlanDialog", "Velocity", None))
        self.label_15.setText(_translate("NewFlightPlanDialog", "XD", None))
        self.label_16.setText(_translate("NewFlightPlanDialog", "YD", None))
        self.label_17.setText(_translate("NewFlightPlanDialog", "ZD", None))
        self.xd_edit.setText(_translate("NewFlightPlanDialog", "0.0", None))
        self.yd_edit.setText(_translate("NewFlightPlanDialog", "0.0", None))
        self.zd_edit.setText(_translate("NewFlightPlanDialog", "0.0", None))
        self.label_18.setText(_translate("NewFlightPlanDialog", "Position and velocity should be J2000 ecliptic coordinate, and units are meter and meter per second.", None))
        self.cancelbutton.setText(_translate("NewFlightPlanDialog", "Cancel", None))
        self.okbutton.setText(_translate("NewFlightPlanDialog", "OK", None))

