# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showorbitcontrol.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ShowOrbitControl(object):
    def setupUi(self, ShowOrbitControl):
        ShowOrbitControl.setObjectName(_fromUtf8("ShowOrbitControl"))
        ShowOrbitControl.resize(640, 211)
        self.label = QtGui.QLabel(ShowOrbitControl)
        self.label.setGeometry(QtCore.QRect(370, 50, 51, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.delta_t_edit = QtGui.QLineEdit(ShowOrbitControl)
        self.delta_t_edit.setGeometry(QtCore.QRect(430, 50, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.delta_t_edit.setFont(font)
        self.delta_t_edit.setAcceptDrops(False)
        self.delta_t_edit.setToolTip(_fromUtf8(""))
        self.delta_t_edit.setObjectName(_fromUtf8("delta_t_edit"))
        self.fastbackward = QtGui.QPushButton(ShowOrbitControl)
        self.fastbackward.setGeometry(QtCore.QRect(370, 100, 41, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fastbackward.setFont(font)
        self.fastbackward.setAutoRepeat(True)
        self.fastbackward.setAutoDefault(False)
        self.fastbackward.setObjectName(_fromUtf8("fastbackward"))
        self.backward = QtGui.QPushButton(ShowOrbitControl)
        self.backward.setGeometry(QtCore.QRect(420, 100, 41, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.backward.setFont(font)
        self.backward.setAutoRepeat(True)
        self.backward.setAutoDefault(False)
        self.backward.setObjectName(_fromUtf8("backward"))
        self.forward = QtGui.QPushButton(ShowOrbitControl)
        self.forward.setGeometry(QtCore.QRect(470, 100, 41, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.forward.setFont(font)
        self.forward.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.forward.setAutoRepeat(True)
        self.forward.setAutoDefault(False)
        self.forward.setObjectName(_fromUtf8("forward"))
        self.fastforward = QtGui.QPushButton(ShowOrbitControl)
        self.fastforward.setGeometry(QtCore.QRect(520, 100, 41, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fastforward.setFont(font)
        self.fastforward.setAutoRepeat(True)
        self.fastforward.setAutoDefault(False)
        self.fastforward.setObjectName(_fromUtf8("fastforward"))
        self.timescale = QtGui.QSpinBox(ShowOrbitControl)
        self.timescale.setGeometry(QtCore.QRect(580, 100, 42, 22))
        self.timescale.setMinimum(-8)
        self.timescale.setMaximum(5)
        self.timescale.setObjectName(_fromUtf8("timescale"))
        self.label_2 = QtGui.QLabel(ShowOrbitControl)
        self.label_2.setGeometry(QtCore.QRect(570, 80, 61, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.ctimeLabel = QtGui.QLabel(ShowOrbitControl)
        self.ctimeLabel.setGeometry(QtCore.QRect(370, 10, 51, 16))
        self.ctimeLabel.setObjectName(_fromUtf8("ctimeLabel"))
        self.label_4 = QtGui.QLabel(ShowOrbitControl)
        self.label_4.setGeometry(QtCore.QRect(370, 30, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.dtApply = QtGui.QPushButton(ShowOrbitControl)
        self.dtApply.setGeometry(QtCore.QRect(555, 49, 41, 23))
        self.dtApply.setAutoDefault(False)
        self.dtApply.setObjectName(_fromUtf8("dtApply"))
        self.label_3 = QtGui.QLabel(ShowOrbitControl)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 161, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_9 = QtGui.QLabel(ShowOrbitControl)
        self.label_9.setGeometry(QtCore.QRect(235, 130, 191, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(ShowOrbitControl)
        self.label_10.setGeometry(QtCore.QRect(10, 150, 61, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(ShowOrbitControl)
        self.label_11.setGeometry(QtCore.QRect(10, 170, 61, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(ShowOrbitControl)
        self.label_12.setGeometry(QtCore.QRect(10, 190, 61, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_14 = QtGui.QLabel(ShowOrbitControl)
        self.label_14.setGeometry(QtCore.QRect(235, 150, 51, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(ShowOrbitControl)
        self.label_15.setGeometry(QtCore.QRect(450, 150, 51, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(ShowOrbitControl)
        self.label_16.setGeometry(QtCore.QRect(235, 170, 51, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(ShowOrbitControl)
        self.label_17.setGeometry(QtCore.QRect(235, 190, 51, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(ShowOrbitControl)
        self.label_18.setGeometry(QtCore.QRect(450, 130, 181, 21))
        self.label_18.setWordWrap(False)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(ShowOrbitControl)
        self.label_19.setGeometry(QtCore.QRect(400, 80, 161, 20))
        self.label_19.setWordWrap(False)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.preddate = QtGui.QLineEdit(ShowOrbitControl)
        self.preddate.setGeometry(QtCore.QRect(430, 29, 201, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.preddate.setFont(font)
        self.preddate.setAcceptDrops(False)
        self.preddate.setToolTip(_fromUtf8(""))
        self.preddate.setFrame(False)
        self.preddate.setReadOnly(True)
        self.preddate.setObjectName(_fromUtf8("preddate"))
        self.RVTvel = QtGui.QLineEdit(ShowOrbitControl)
        self.RVTvel.setGeometry(QtCore.QRect(290, 149, 141, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.RVTvel.setFont(font)
        self.RVTvel.setToolTip(_fromUtf8(""))
        self.RVTvel.setFrame(False)
        self.RVTvel.setReadOnly(True)
        self.RVTvel.setObjectName(_fromUtf8("RVTvel"))
        self.RVTphi = QtGui.QLineEdit(ShowOrbitControl)
        self.RVTphi.setGeometry(QtCore.QRect(290, 169, 141, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.RVTphi.setFont(font)
        self.RVTphi.setToolTip(_fromUtf8(""))
        self.RVTphi.setFrame(False)
        self.RVTphi.setReadOnly(True)
        self.RVTphi.setObjectName(_fromUtf8("RVTphi"))
        self.RVTelv = QtGui.QLineEdit(ShowOrbitControl)
        self.RVTelv.setGeometry(QtCore.QRect(290, 189, 141, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.RVTelv.setFont(font)
        self.RVTelv.setToolTip(_fromUtf8(""))
        self.RVTelv.setFrame(False)
        self.RVTelv.setReadOnly(True)
        self.RVTelv.setObjectName(_fromUtf8("RVTelv"))
        self.groupBox = QtGui.QGroupBox(ShowOrbitControl)
        self.groupBox.setGeometry(QtCore.QRect(250, 10, 101, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.man_elv = QtGui.QLabel(self.groupBox)
        self.man_elv.setGeometry(QtCore.QRect(30, 60, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.man_elv.setFont(font)
        self.man_elv.setText(_fromUtf8(""))
        self.man_elv.setObjectName(_fromUtf8("man_elv"))
        self.man_dv = QtGui.QLabel(self.groupBox)
        self.man_dv.setGeometry(QtCore.QRect(30, 20, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.man_dv.setFont(font)
        self.man_dv.setText(_fromUtf8(""))
        self.man_dv.setObjectName(_fromUtf8("man_dv"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 21, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 21, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 21, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.man_phi = QtGui.QLabel(self.groupBox)
        self.man_phi.setGeometry(QtCore.QRect(30, 40, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.man_phi.setFont(font)
        self.man_phi.setText(_fromUtf8(""))
        self.man_phi.setObjectName(_fromUtf8("man_phi"))
        self.groupBox_2 = QtGui.QGroupBox(ShowOrbitControl)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 71, 111))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tobarycenter = QtGui.QRadioButton(self.groupBox_2)
        self.tobarycenter.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.tobarycenter.setChecked(True)
        self.tobarycenter.setObjectName(_fromUtf8("tobarycenter"))
        self.toprobe = QtGui.QRadioButton(self.groupBox_2)
        self.toprobe.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.toprobe.setObjectName(_fromUtf8("toprobe"))
        self.totarget = QtGui.QRadioButton(self.groupBox_2)
        self.totarget.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.totarget.setObjectName(_fromUtf8("totarget"))
        self.groupBox_3 = QtGui.QGroupBox(ShowOrbitControl)
        self.groupBox_3.setGeometry(QtCore.QRect(90, 10, 151, 111))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.check_Ptrj = QtGui.QCheckBox(self.groupBox_3)
        self.check_Ptrj.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.check_Ptrj.setChecked(True)
        self.check_Ptrj.setObjectName(_fromUtf8("check_Ptrj"))
        self.showplanets = QtGui.QCheckBox(self.groupBox_3)
        self.showplanets.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.showplanets.setChecked(True)
        self.showplanets.setObjectName(_fromUtf8("showplanets"))
        self.check_PKepler = QtGui.QCheckBox(self.groupBox_3)
        self.check_PKepler.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.check_PKepler.setChecked(True)
        self.check_PKepler.setObjectName(_fromUtf8("check_PKepler"))
        self.check_TKepler = QtGui.QCheckBox(self.groupBox_3)
        self.check_TKepler.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.check_TKepler.setChecked(True)
        self.check_TKepler.setObjectName(_fromUtf8("check_TKepler"))
        self.currentdate = QtGui.QLineEdit(ShowOrbitControl)
        self.currentdate.setGeometry(QtCore.QRect(430, 9, 201, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.currentdate.setFont(font)
        self.currentdate.setAcceptDrops(False)
        self.currentdate.setToolTip(_fromUtf8(""))
        self.currentdate.setFrame(False)
        self.currentdate.setReadOnly(True)
        self.currentdate.setObjectName(_fromUtf8("currentdate"))
        self.RPTrange = QtGui.QLineEdit(ShowOrbitControl)
        self.RPTrange.setGeometry(QtCore.QRect(75, 149, 141, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.RPTrange.setFont(font)
        self.RPTrange.setToolTip(_fromUtf8(""))
        self.RPTrange.setFrame(False)
        self.RPTrange.setReadOnly(True)
        self.RPTrange.setObjectName(_fromUtf8("RPTrange"))
        self.RPTphi = QtGui.QLineEdit(ShowOrbitControl)
        self.RPTphi.setGeometry(QtCore.QRect(75, 169, 141, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.RPTphi.setFont(font)
        self.RPTphi.setToolTip(_fromUtf8(""))
        self.RPTphi.setFrame(False)
        self.RPTphi.setReadOnly(True)
        self.RPTphi.setObjectName(_fromUtf8("RPTphi"))
        self.RPTelv = QtGui.QLineEdit(ShowOrbitControl)
        self.RPTelv.setGeometry(QtCore.QRect(75, 189, 141, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.RPTelv.setFont(font)
        self.RPTelv.setToolTip(_fromUtf8(""))
        self.RPTelv.setFrame(False)
        self.RPTelv.setReadOnly(True)
        self.RPTelv.setObjectName(_fromUtf8("RPTelv"))
        self.LoSVvel = QtGui.QLineEdit(ShowOrbitControl)
        self.LoSVvel.setGeometry(QtCore.QRect(503, 149, 131, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.LoSVvel.setFont(font)
        self.LoSVvel.setToolTip(_fromUtf8(""))
        self.LoSVvel.setFrame(False)
        self.LoSVvel.setReadOnly(True)
        self.LoSVvel.setObjectName(_fromUtf8("LoSVvel"))
        self.groupBox_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.delta_t_edit.raise_()
        self.fastbackward.raise_()
        self.forward.raise_()
        self.fastforward.raise_()
        self.timescale.raise_()
        self.ctimeLabel.raise_()
        self.label_4.raise_()
        self.dtApply.raise_()
        self.label_3.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.preddate.raise_()
        self.RVTvel.raise_()
        self.RVTphi.raise_()
        self.RVTelv.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.backward.raise_()
        self.currentdate.raise_()
        self.RPTrange.raise_()
        self.RPTphi.raise_()
        self.RPTelv.raise_()
        self.LoSVvel.raise_()

        self.retranslateUi(ShowOrbitControl)
        QtCore.QMetaObject.connectSlotsByName(ShowOrbitControl)
        ShowOrbitControl.setTabOrder(self.tobarycenter, self.toprobe)
        ShowOrbitControl.setTabOrder(self.toprobe, self.totarget)
        ShowOrbitControl.setTabOrder(self.totarget, self.fastbackward)
        ShowOrbitControl.setTabOrder(self.fastbackward, self.backward)
        ShowOrbitControl.setTabOrder(self.backward, self.forward)
        ShowOrbitControl.setTabOrder(self.forward, self.fastforward)
        ShowOrbitControl.setTabOrder(self.fastforward, self.preddate)
        ShowOrbitControl.setTabOrder(self.preddate, self.delta_t_edit)
        ShowOrbitControl.setTabOrder(self.delta_t_edit, self.dtApply)
        ShowOrbitControl.setTabOrder(self.dtApply, self.timescale)

    def retranslateUi(self, ShowOrbitControl):
        ShowOrbitControl.setWindowTitle(_translate("ShowOrbitControl", "Show Orbit", None))
        self.label.setText(_translate("ShowOrbitControl", "DT(days)", None))
        self.fastbackward.setToolTip(_translate("ShowOrbitControl", "Fast Backword", None))
        self.fastbackward.setText(_translate("ShowOrbitControl", "<<", None))
        self.backward.setToolTip(_translate("ShowOrbitControl", "Backward", None))
        self.backward.setText(_translate("ShowOrbitControl", "<", None))
        self.forward.setToolTip(_translate("ShowOrbitControl", "Forward", None))
        self.forward.setText(_translate("ShowOrbitControl", ">", None))
        self.fastforward.setToolTip(_translate("ShowOrbitControl", "Fast Forward", None))
        self.fastforward.setText(_translate("ShowOrbitControl", ">>", None))
        self.timescale.setToolTip(_translate("ShowOrbitControl", "Select exponent", None))
        self.label_2.setText(_translate("ShowOrbitControl", "Scale 10**", None))
        self.ctimeLabel.setText(_translate("ShowOrbitControl", "Current", None))
        self.label_4.setText(_translate("ShowOrbitControl", "Seeing", None))
        self.dtApply.setText(_translate("ShowOrbitControl", "Apply", None))
        self.label_3.setText(_translate("ShowOrbitControl", "Relative Position of Target", None))
        self.label_9.setText(_translate("ShowOrbitControl", "Relative Velocity of Target", None))
        self.label_10.setText(_translate("ShowOrbitControl", "range (km)", None))
        self.label_11.setText(_translate("ShowOrbitControl", "phi (deg)", None))
        self.label_12.setText(_translate("ShowOrbitControl", "elv (deg)", None))
        self.label_14.setText(_translate("ShowOrbitControl", "vel (m/s)", None))
        self.label_15.setText(_translate("ShowOrbitControl", "vel (m/s)", None))
        self.label_16.setText(_translate("ShowOrbitControl", "phi (deg)", None))
        self.label_17.setText(_translate("ShowOrbitControl", "elv (deg)", None))
        self.label_18.setText(_translate("ShowOrbitControl", "Line of Sight Velocity (departing)", None))
        self.label_19.setText(_translate("ShowOrbitControl", "Prediction Time Manipulator", None))
        self.groupBox.setTitle(_translate("ShowOrbitControl", "Mn Parameters", None))
        self.label_8.setText(_translate("ShowOrbitControl", "elv", None))
        self.label_6.setText(_translate("ShowOrbitControl", "dv", None))
        self.label_7.setText(_translate("ShowOrbitControl", "phi", None))
        self.groupBox_2.setTitle(_translate("ShowOrbitControl", "Look at", None))
        self.tobarycenter.setToolTip(_translate("ShowOrbitControl", "Solar System Barycenter", None))
        self.tobarycenter.setText(_translate("ShowOrbitControl", "SSB", None))
        self.toprobe.setText(_translate("ShowOrbitControl", "Probe", None))
        self.totarget.setText(_translate("ShowOrbitControl", "Target", None))
        self.groupBox_3.setTitle(_translate("ShowOrbitControl", "Show", None))
        self.check_Ptrj.setText(_translate("ShowOrbitControl", "Probe Trajectory", None))
        self.showplanets.setText(_translate("ShowOrbitControl", "Planets", None))
        self.check_PKepler.setText(_translate("ShowOrbitControl", "Probe Kepler Orbit", None))
        self.check_TKepler.setText(_translate("ShowOrbitControl", "Target Kepler Orbit", None))

